---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: quay.io/desource/alpine-build

run:
  path: src/build.sh
    
inputs:
  - name: libressl-src
    path: src

outputs:
  - name: libressl
  
